version: 2.1

jobs:
  Setup_aws:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk update
            apk add --no-cache aws-cli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Init and Plan
          command: |
            cd env/dev
            terraform init
            terraform plan

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: |
            cd env/dev
            terraform init
      - run:
          name: Terraform Apply
          command: |
            cd env/dev
            terraform apply -auto-approve
            terraform output -raw Public_IP > public_ip.txt
            cat public_ip.txt

  terraform_destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: |
            cd env/dev
            terraform init
      - run:
          name: Terraform Destroy
          command: |
            cd env/dev
            terraform destroy -auto-approve
  

workflows:
  version: 2
  terraform_flow:
    jobs:
      - Setup_aws
      - terraform_plan:
          requires:
            - Setup_aws
      - hold1:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          requires:
            - hold
      - hold:
          type: approval
          requires:
            - terraform_plan
      - terraform_destroy:
          requires:
            - hold1
            